### ISSUE TITLE
String Compatibility in Send Message

### ISSUE THREAD

**Issue by liamhebert** [AndrewWay/cubesat#19]
As a user of the message sending interface, I would greatly appreciate the ability to use strings to send information downstream. This allows for enhanced information between subsystems without having to translate down to floats or int, where info could be lost

**Comment by s-axford** [comment]
I will be looking at adding this next week. Stay tuned.

**Comment by liamhebert** [comment]
We found a solution for our purpose using bitshifts and ints but this would be much simpler

**Comment by s-axford** [comment]
Functionality has been added, closing this issues. Please message me if any bugs occur that I may have missed.
