### ISSUE TITLE
(Bug?) SerializeMessage() and DeserializeMessage() should live in MessageSerializer.cpp instead of in header

### ISSUE THREAD

**Issue by jporterdal** [AndrewWay/cubesat#21]
Bug-with-a-question-mark.

The code for these titular functions is defined (not just declared) inside the MessageSerializer header file:
[/core/src/message/header/MessageSerializer.h](https://github.com/AndrewWay/cubesat/blob/master/core/src/message/header/MessageSerializer.h)

AFAIK, this leads to linking errors as there can be multiple definitions of these two functions if #include-d from multiple source files.

**Comment by s-axford** [comment]
That file is no longer being used and will likely be removed in the next release. I will remove it from develop branch.

**Comment by s-axford** [comment]
For reference, that code is revised and has become the flatten method in Message.cc

**Comment by liamhebert** [comment]
Do you think we could start adding `DEPRECATED` tags to old files? I believe this issue highlights an important problem since more repos/teams will begin looking at this repository

**Comment by s-axford** [comment]
Yes @liamhebert you are right. I just fixed the deprecated content I am aware of in the internal-message library with a PR to develop, and will search for anymore deprecated content this weekend.

**Comment by liamhebert** [comment]
Fantastic, thanks @s-axford !!
