### ISSUE TITLE
Architectural Diagrams uploaded on Readme.md

### ISSUE THREAD

**Issue by liamhebert** [AndrewWay/cubesat#51]
It would be nice to have some diagrams uploaded on the readme.md, makes it nice to get an idea of the structure of files

**Comment by amellalalex** [comment]
Hey liam, long time no see. Great to get some of your feedback. The file structure of the repo is definitely messy and in need of some cleaning up and mapping/direction. At the moment, there is documentation being generated at http://cubesat.alexamellal.com to provide guidance and information on the core software. In the meantime, it should be enough to do some preliminary testing and buy some time to clean up and map the repo later.

If you have any specific questions about the purpose of certain folders or files don't hesitate in asking me
